### ISSUE TITLE
SA2 Feature Request - 

### ISSUE THREAD

**Issue by mikael1000** [mhs/scout-app#1]
Nothing about getting started with this. No tutorials on Youtube that isn't outdated? Is this only for those who know this "since before"?

**Comment by TheJaredWilcurt** [comment]
We are in the process of transferring repos. Can you close this and reopen it over here:
- https://github.com/scout-app/scout-app/issues

A "getting started" video has been recorded, it is in the process of being edited and will be on the website next to the download buttons. There is currently a placeholder video.
- http://Scout-App.io

We also welcome those in the community to create tutorial videos.

**Comment by TheJaredWilcurt** [comment]
This issue can be closed.
- https://www.youtube.com/watch?v=6zA78zMsH9w

**Comment by mikael1000** [comment]
Good work!
