### ISSUE TITLE
Where can I see current installed version?

### ISSUE THREAD

**Issue by nilovelez** [mhs/scout-app#206]
I think I'm running version 0.7.1 on Windows, but I can't find the installed version number anywhere. When new versions are released I won't be able to determine if they are newer than mine.

**Comment by TheJaredWilcurt** [comment]
A newer version has not been released in a long time. There is a plan in the works for a newer version however.

To answer your question, I don't know of a way to find this through the app, but if you go into its install directory you can open the `production.xml` it should say the version there.

* C:\Program Files (x86)\Scout\production.xml

**Comment by nilovelez** [comment]
Yes, I've found the version number on `production.xml`, thank you for your help.

Anyway, it won't hurt to have the version number on the interface of the program. Maybe on the startup log or the title bar?
