### ISSUE TITLE
Unable to run foundation 6 alpha through Scout

### ISSUE THREAD

**Issue by apcrane** [mhs/scout-app#220]
Are you looking to upgrade Scout anytime soon with the latest SASS/Compass versions? Since I have been using your product for quite a while now with great success to compile my SCSS. However, I'm trialing Foundation 6 alpha (which is estimated to become a public release next week) and certain SCSS rules won't allow me to compile into CSS any more. For instance, an error I receive when trying to run the project:

Invalid CSS after " top": expected ")", was ": nth($val, 1),")

**Comment by TheJaredWilcurt** [comment]
Current version of Scout-App is from 2012. There are [talks](https://github.com/mhs/scout-app/issues/186) of creating a new version using [NW.js](http://nwjs.io) and likely the [UGUI](http://ugui.io) framework for it as it is cross platform (Ubuntu 12+, OSX 10.9+, and Windows Vista+) and seems to be the most reliable way for ease of updating in the future.

I attempted several months back while UGUI was still in development to create one using NW.js without UGUI and found that it would be much easier after UGUI was completed. Now it is, but I'm currently tied up with other commitments to work on Scout. It's next on my list though. So development on this new successor will begin soon, but don't expect it out for a while. October-December is always a busy time of year for me. So I may be able to look at it in January.

**Comment by apcrane** [comment]
Many thanks for getting back to me about your plans for the next release of Scout. I look forward to seeing this in the new year. In the meantime is there any way of upgrading the the SASS version that Scout uses?

**Comment by TheJaredWilcurt** [comment]
The amount of complexity in updating Sass in the current version would outweigh the effort of setting up a build system using Grunt or Gulp. For now you can either wait a little while for the new version of Scout, alter the code you'll be using to reflect the capabilities of previous versions of Sass, or use an alternative way to compile your Sass files with one of these alternative methods:

* [Compass.app](http://compass.kkbox.com) (Paid, comes with latest Sass/Compass)
* [Prepros](http://alphapixels.com/prepros/) (Paid, comes with latest Sass/Compass)
* [Koala](http://koala-app.com) (Free, comes with Sass/Compass)
* [Mixture](http://mixture.io/) (Paid, comes with Sass/Compass)
* [LiveReload](http://livereload.com) (Paid, comes with Sass/Compass)
* [Codekit](http://incident57.com/codekit/) (Paid, Mac only, comes withSass/Compass)
* [Hammer](http://hammerformac.com/news/compass.html) (Paid, Mac only, no Compass)
* [Ruby](https://www.ruby-lang.org) + [Compass](http://compass-style.org) + [Sass](http://sass-lang.com/install) (The original, Free)
* [Node.JS](https://nodejs.org) + [Grunt](http://gruntjs.com) + [Ruby](https://www.ruby-lang.org) + [Compass](http://compass-style.org) + [Grunt-Contrib-Sass](https://github.com/gruntjs/grunt-contrib-sass) (Free, Sass/Compass)
* [Node.JS](https://nodejs.org) + [Grunt](http://gruntjs.com) + [Grunt-Sass](https://www.npmjs.org/package/grunt-sass) + [Compass Mixins](https://github.com/Igosuki/compass-mixins) (Free, C++ Version, faster, almost all Compass needs resolved)
* [Node.JS](https://nodejs.org) + [Gulp](http://gulpjs.com) + [Gulp-Sass](https://www.npmjs.com/package/gulp-sass) + [Compass Mixins](https://github.com/Igosuki/compass-mixins) (Free, C++ Version, faster, almost all Compass needs resolved)

**Comment by apcrane** [comment]
Ok thanks for confirming. I have consequently managed to get this code compiled using Compass.app.
