### ISSUE TITLE
Scout App for Sass

### ISSUE THREAD

**Issue by soumyahooli** [mhs/scout-app#227]
Ruby is working fine on my machine. When tried to install Scout app form the following link https://mhs.github.io/scout-app/ I could download .exe file for windows machine. But when tried to install, error occurred saying-The application could not be installed because the installer file is damaged. Try obtaining a new installer file from the application author.

**Comment by TheJaredWilcurt** [comment]
See: https://github.com/mhs/scout-app/issues/228

**Comment by soumyahooli** [comment]
@TheJaredWilcurt .. followed the instructions given.. but it is giving same error again
Please help

**Comment by TheJaredWilcurt** [comment]
@soumyahooli 

> installation was success

Can you close this Issue then?

**Comment by HongNhatNguyen** [comment]
1.Download ->Scout App
2Download-> 7-Zip and install it
3.Right-click ScoutAppInstaller-0.7.1.exe > 7-Zip > Extract to "ScoutAppInstaller-0.7.1/"
4.Open file Scout ->setup.msi install      OK!
if still can not install, please install:
Install Adobe AIR.
Install Adobe Muse.

"Success"
