### ISSUE TITLE
Installer for windows is not working

### ISSUE THREAD

**Issue by baffourasante** [mhs/scout-app#229]
Installer for windows is not working

**Comment by TheJaredWilcurt** [comment]
Please close this issue and refer to #228.

**Comment by TheJaredWilcurt** [comment]
@baffourasante Please close this issue:

Download and follow the instructions included.

* **[Scout-App 0.7.1 for Windows Re-Release](https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10)**

**Comment by kaichi** [comment]
im having the same issue

**Comment by TheJaredWilcurt** [comment]
@baffourasante

## Download and follow the instructions included.

* **[Scout-App 0.7.1 for Windows Re-Release](https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10)**

**Comment by baffourasante** [comment]
Thanks you it worked
