### ISSUE TITLE
cannot download windows installer

### ISSUE THREAD

**Issue by claudioimai** [mhs/scout-app#238]
I'm trying to download the ScoutApp for windows, but could not even start the download.

As soon as I click on the download link, I get an error message stating a network failure.
FYI, I tried on Firefox, Chrome, Internet explorer 10 on Windows 7 64 bits, and Chrome in my Android phone. No luck so far.

I can't tell if it's only me (my local network) or if it's a general problem. Any advice?

UPDATE: I finally could download the file, but from a link in the "issues" site: 
https://github.com/downloads/mhs/scout-app/ScoutAppInstaller-0.7.1.exe
Looks like the main link is broken somehow.

Then again, the installer throws an error, which I could solve by following this link: 
<a href="https://github.com/mhs/scout-app/issues/228" target="_blank">https:// github.com/mhs/scout-app/issues/228</a>

**Comment by TheJaredWilcurt** [comment]
Known issue. There is a re-release with instructions on how to install it the 2012 version. Or you can try the 2016 version that is in Beta (soon to be released).

* https://github.com/TheJaredWilcurt/scout-app/releases

If that works for you, you can close this ticket.

**Comment by claudioimai** [comment]
The real issue is not fixed, though the problem for me was solved by using the beta version as suggested.

IMHO, there could be a note near the official download link about this situation. It would probably save a lot of repeating questions and answers, since I myself looked through the issues site and could not find a direct answer, thus starting this thread...

**Comment by TheJaredWilcurt** [comment]
We're currently working on the website for the new app. So hopefully this won't be an issue for much longer.
