### ISSUE TITLE
Application install error

### ISSUE THREAD

**Issue by mihaigeorgeforlafu** [mhs/scout-app#242]
"The application could not be installed because the installer file is damaged. Try obtaining a new installer from the application author.
![scout-error](https://cloud.githubusercontent.com/assets/7272170/15991829/b5ab504a-30be-11e6-9bd7-9f1c1a0f764d.PNG)
"

**Comment by TheJaredWilcurt** [comment]
There is a Scout-App 0.7.1 (2012) re-release for Windows that covers new installation errors.

Or you can try the 2016 Scout-App 2 (beta)

* http://github.com/TheJaredWilcurt/scout-app/releases

If that works for you, close this ticket.

**Comment by mihaigeorgeforlafu** [comment]
Thanks
