### ISSUE TITLE
@import of google font Open Sans causes compile syntax error 

### ISSUE THREAD

**Issue by geoidesic** [mhs/scout-app#249]
E.g. `@import "https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i";
`

This results in the following error:

> Syntax error: File to import not found or unreadable: https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i.

The issue may be related to this answer:

> http://stackoverflow.com/questions/32001352/gulp-sass-compiles-google-fonts-css-into-the-file-breaks-protocol-relative-link#answer-32001551

**Comment by TheJaredWilcurt** [comment]
@geoidesic 

I tested in [Scout-App v2.0.2](http://scout-app.io) (latest-stable) and it seems to be working. If you aren't using that version, switch to it. If you are using that version, supply more information about your file that is importing the font.

**Input:** `style.scss`

```
@charset "utf-8";
@import "https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i";
@import "_meyer.sass"; // http://meyerweb.com/eric/tools/css/reset
```

**Output:** `style.css:`

```
@import "https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i";
html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,
cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,
ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,
embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{
border:0px;margin:0px;padding:0px;font-size:100%;font:inherit;vertical-align:baseline}article,aside,
details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block}body{line-height:1}ol,ul{
list-style:none}blockquote,q{quotes:none}blockquote:before,blockquote:after,q:before,q:after{content:'';
content:none}table{border-collapse:collapse;border-spacing:0}
```

**Comment by geoidesic** [comment]
Thanks. I was using v0.7.1! The new version handles this without issue.
